### ISSUE TITLE
Recommend moving to AGPLv3 instead of GPLv3 to prevent non-distributed proprietary forks

### ISSUE THREAD

**Issue by rodneyrod** [eris-ltd/2gather#55]
GPLv3 only kicks in if the modified product is distributed. AGPLv3 sorts this out by requiring the source to all modifications to be released regardless of whether or not they're being distributed.

Greater work provisions also means that if you apply AGPLv3 to any file within this project, the entire project has to be distributed as AGPLv3.

**Comment by compleatang** [comment]
Thanks @rodneyrod for the recommendation. At this time we are satisfied with GPLv3 and we are OK with the differences between it and AGPLv3. 

As a bit of background, this application has been built primarily *as an example* (rather than as a production application) and we have no problem with folks forking and working on other applications based on it.
